### ISSUE TITLE
Cannot redeclare __()?

### ISSUE THREAD

**Issue by iwillhappy1314** [laraish/laraish#1]
```
php artisan package:discover
PHP Fatal error:  Cannot redeclare __() (previously declared in /Users/Amoslee/Sites/wizhi/wp-content/themes/laravel/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:907) in /Users/Amoslee/Share/wordpress/wp-includes/l10n.php on line 203
```

the function `__() ` from Illuminate confilict with wordpress`s function

**Comment by yaquawa** [comment]
Yes, you're right. As of Laravel 5.4 a helper function `__` was added; which the name is the same as WordPress's.

So I've renamed the Laravel's `__` to `___` to avoid the conflict.

If you do `composer update` or install the framework with `composer create-project --prefer-dist laraish/laraish <theme-name>` it should run the `Laraish\\Foundation\\ComposerScripts::renameHelperFunctions` to rename the Laravel's helper function `__` to `___`.

Good luck.

**Comment by iwillhappy1314** [comment]
add the command: `Laraish\\Foundation\\ComposerScripts::renameHelperFunctions` to `post-autoload-dump` script, before `"Illuminate\\Foundation\\ComposerScripts::postAutoloadDump"`,

the error disappeared.

**Comment by yaquawa** [comment]
@iwillhappy1314 Thanks for your feedback.
