### ISSUE TITLE
I created a video on how to use this theme ;)

### ISSUE THREAD

**Issue by tnylea** [laraish/laraish#12]
Hey Guys,

Great work! I love having the ability to use Laravel in a WP Theme.

Just wanted to send over this link to you in case you want to include it in your Readme file: [https://devdojo.com/episode/laraish](https://devdojo.com/episode/laraish)

I created a video showing how to set up the theme and how cool it is. Anyway, hope all is going well.

**Comment by yaquawa** [comment]
Thanks @tnylea !!
I would appreciate it if you would send me a PR for the readme file as well.
