### ISSUE TITLE
Best practice for integrating authentication system

### ISSUE THREAD

**Issue by Stevemoretz** [laraish/laraish#13]
Hi Laravel has its own authentication system, and Wordpress also has its own one.
So shall we let go of the laravel authentication system?
and make a custom middleware for authentication 'auth'
and also one for 'auth:api'?

**Comment by yaquawa** [comment]
You can create your own one with `is_admin()` function very easily if needed.

**Comment by Stevemoretz** [comment]
Yeah tnx, that'll work I thought maybe you somehow integrated the login system of laravel with WordPress.
