### ISSUE TITLE
Nothing returns if visit chosen A Static Posts page

### ISSUE THREAD

**Issue by Stevemoretz** [laraish/laraish#14]
In
**Reading Settings**
Your homepage displays : 
if you choose :  A static page (select below)
and select a Posts page : whatever
then if you visit that page :
http://localhost:3000/whatever/
The source of the page would be completely empty.

I'm using laraish as a child theme right now if it has anything to do with this problem?
And I changed the Posts page to something else
http://localhost:3000/whatever/
returns some html
and the other chosen page would return nothing.

**Comment by yaquawa** [comment]
The quick answer is that it can't used as a regular child theme.

**Comment by Stevemoretz** [comment]
I don't want it as a regular it's totally fine because laraish isn't a regular theme so why would its child theme version would be?but would you please guide me how to set it up in a way that works?

**Comment by Stevemoretz** [comment]
The problem is that the blog page is powered by index.php and laraish has a index.php which is empty so just copy and paste the index.php from the parent theme and your blog starts working :)
