### ISSUE TITLE
Can't use it as a child theme

### ISSUE THREAD

**Issue by Stevemoretz** [laraish/laraish#15]
Hi I'm trying to use this great theme as a child theme I did set it as a child theme and everything is working I even could add the styles and everything.But I don't know how to override the php files now.Imagine I want to change the front_page or any other page.I used:

`Route::any('front_page','FrontController@index');`

inside web.php but it has no effect at all.and also:

```
Route::any('home', 'Generic\Home@index');
Route::any('single', 'Generic\Single@index');
Route::any('page', 'Generic\Page@index');
Route::any('404', 'Generic\NotFound@index');
```

All these defaults are not working anymore and everything is coming from the parent theme.

Also the laravel router is not working anymore and is giving 404.

So would you please show me what to do?I want to use laraish as a child theme but couldn't find a way yet.

**Comment by yaquawa** [comment]
Yes you can't use it as a child theme because of the mechanism of WordPress loading the template files.

**Comment by Stevemoretz** [comment]
No workarounds?Can't we use php directly instead of blade for child themes?

**Comment by yaquawa** [comment]
> Can't we use php directly instead of blade for child themes?
Yes you can. Just create a php file like `single.php` then WordPress will use that file normally.

**Comment by Stevemoretz** [comment]
Well I'll try that, just put it in inside the main folder right?That'll be nice thank you.I'll try and I'll report here

**Comment by Stevemoretz** [comment]
This simply worked and you can still use all laravel in the php file but of course not blade stuff.
