### ISSUE TITLE
Im getting an error establishing a connection to database

### ISSUE THREAD

**Issue by rovillesarate** [laraish/laraish#16]
Hi after installing laraish. i keep getting an error Error establishing a database connection

I am using mamp pro so i made sure the server and mysql is running but it does not work. even after putting the mysql database manually on the .env file.

**Comment by yaquawa** [comment]
see https://github.com/laraish/laraish#run-artisan-command

**Comment by rovillesarate** [comment]
Finally fixed the problem. if your using mac and mamp for this. set this on your wp-config file

`define( 'DB_HOST', 'localhost:/Applications/MAMP/tmp/mysql/mysql.sock' );`

**Comment by Alexlytle** [comment]
Any suggestions to get this running on windows?
