### ISSUE TITLE
Having problem with using controller in routes

### ISSUE THREAD

**Issue by rovillesarate** [laraish/laraish#17]
Hi! I was able to finally get things working but im having some problems with using controllers on Routes.
// does not work
`Route::get('account/login')->name('login')->uses('Auth\LoginController@showLoginForm')->middleware('guest'); `

// this seems to work
```
Route::get('account/login', function() {
    return Inertia::render('Auth/Login');
})->middleware('guest');
```

when using controller on routes i get the following error
![image](https://user-images.githubusercontent.com/2109352/87905201-93af5a00-ca92-11ea-9329-2c732adf2577.png)
no additional information for whats causing the problem, even if debug and error reporting is turned on.

another issue i found is that the public folder for css and js returns a 404 error. already check the .htaccess. everything seems to be in place.

**Comment by rovillesarate** [comment]
when installing laravel you need to point the server to the public folder so i wonder.. in laraish since the laravel is inside the theme how do you point it to the public folder?

**Comment by rovillesarate** [comment]
was able to fix the problem with the controller. you need to composer require laravel/ui on your theme directory. Only thing need fixing now is the public folder js and css getting 404 error.

**Comment by rovillesarate** [comment]
Already figured out how to make this work. for assets like CSS and js. you can write a .htaccess on the wp-content directory

```
RewriteRule ^css/(.*)$ /wp-content/themes/theme/public/css/$1 [L]
RewriteRule ^js/(.*)$ /wp-content/themes/theme/public/js/$1 [L]
```
so instead of loading CSS and JS this way 
`http://www.yourdomain.com/wp-content/themes/theme/public/css/app.css`
`http://www.yourdomain.com/wp-content/themes/theme/public/js/app.js`

it will now work like this
`http://www.yourdomain.com/css/app.css`
`http://www.yourdomain.com/js/app.js`

Hope this will help. Thanks

**Comment by yaquawa** [comment]
@rovillesarate Thanks.
Or you can write it like this.

```blade
<script src="{{ public_url('js/app.js') }}"></script>
```

**Comment by yaquawa** [comment]
Make sure place the routes above WordPress specific route.
