### ISSUE TITLE
The equipment to index.php

### ISSUE THREAD

**Issue by Stevemoretz** [laraish/laraish#18]
Hi first of all thank you for this great package and also I got some news I've been trying to make an script which (almost) automatically (depending on the theme) will convert a normal theme into this theme basically, splits the theme into different parts puts assets to public folder and makes all php files which have something to show (not the config and only php logic files), into blade files and just make everything fit into laravel  I'd love to share this script with you when it's done and I've worked really hard on it and I want you to have a look at it maybe you like it.please send me your email or something thanks.

So the question is that index.php can't just be the index.php of the theme because it gets added to the end of pages and post pages and that's weird but anyways, so it must be empty not to cause this issue.But I was wondering where shall I put the index.php theme's file in laraish.

**Comment by yaquawa** [comment]
Hi @Stevemoretz
Wow! you've got some really interesting idea💖 Thanks for sharing me this.

As for the index.php, there is no hard rules, it's all about the routes.
But I often put it in the `views/generic/home.blade.php`.

**Comment by Stevemoretz** [comment]
So the home route will do the same thing as index.php?
And BTW I'm happy that you're happy about it, this is my email address:
Sm.steve.moretz@gmail.com
Send me a message so we can discuss this further and I'll send you the script when it's done.

**Comment by yaquawa** [comment]
Hi @Stevemoretz 
I just want let you know I've released a major update to this lib.
Routing stuff have got changed a lot, you may take a look at the new readme.
https://github.com/laraish/laraish#routing

**Comment by Stevemoretz** [comment]
> Hi @Stevemoretz
> I just want to let you know I've released a major update of this lib.
> Routing stuff have got changed a lot, you might want to take a look at the new readme.
> https://github.com/laraish/laraish#routing

Very good news I got some good news too.I fooled around with your UriValidator a bit and also laravel Route.php and could get parameter routing work on your library. Means:

page.test/{hello}

Now passes hello just like what laravel does, and also it's accessible through query_params so could be used from there too, the way I did it was first I wrote a class which takes the route uri:

page.test/{hello}

And then uses WordPress rewrite rules and converterts that to regex also remove page at the beginning and now that could work then again the only reason the laravel parameters don't work is page.something that page doesn't exist in the url so I put some regex in Route.php which would remove that page. And then it was fixed.

Now I can use almost anything.

page.test/{hello}/{hi}/{keepgoing}

And it works all flawlessly, one more point is it uses the last aceesible page in the url as the default page for this new url with parameters but this behavior could change if you think so.

So I've done this all and I'm ready to share all the code with you it's already done.How can we talk somewhere else and I can share the code with you if you are interested?So you can integrate it with your new changes.

Just email me and let me give you all the code and information.

Sm.steve.moretz@gmail.com

This is my email.

**Comment by yaquawa** [comment]
Hi @Stevemoretz thanks for sharing that 🙏🏼

I'm wondering why not you just use a regular Laravel route instead? 

```php
use Illuminate\Support\Facades\Route;

Route::get('/test/{hello}/{foo}/{bar}', 'TestPage@index');
```

That's simple and easy.

**Comment by Stevemoretz** [comment]
> Hi @Stevemoretz thanks for sharing that 🙏🏼
> 
> I'm wondering why not you just use a regular Laravel route instead?
> 
> ```
> use Illuminate\Support\Facades\Route;
> 
> Route::get('/test/{hello}/{foo}/{bar}', 'TestPage@index');
> ```
> 
> simple and easy.

Well that's right but this doesn't give you any pages from WordPress. Oh well maybe I did over complicate it you're right all it needs is another parameter to get the post or page from WordPress.This makes more sense.

Route::get('/test/{hello}/{foo}/{bar}', 'TestPage@index','slug_of_page');

Now since I saw you did your new Facade for WordPress routing,you think maybe it's a good idea to implement this on that?Or something similar.Like just putting the third argument to true then it resolves it by default from the rest of the url.

'/test/{hello}/{foo}/{bar}'

So finds the first {.*} selects before it and it is test  now it tries to fetch test page if it exists it's pretty simple to implement in these ways than what I've done previously.😂

I was actually a little curious about what you've done in there that's why I dug into and did all those stuff otherwise there were easier ways as you mentioned.

**Comment by yaquawa** [comment]
@Stevemoretz In your case '/test/{hello}/{foo}/{bar}', where `test` is a WordPress page right ?
The URI structure looks a bit weird for me, because it could be a child page or descendant page of the page `test`.
Maybe all you need is just a [rewrite endpoint](https://codex.wordpress.org/Rewrite_API/add_rewrite_endpoint)?

Anyway, in my opinion I would get the parameter by query string directly.

**Comment by Stevemoretz** [comment]
> @Stevemoretz In your case `/test/{hello}/{foo}/{bar}`, where `test` is a WordPress page right ?
> The URI structure looks a bit weird for me, because it could be a child page or descendant page of the page `test`.
> Maybe all you need is just a [rewrite endpoint](https://codex.wordpress.org/Rewrite_API/add_rewrite_endpoint)?
> 
> Anyway, in my opinion I would get the parameter by query string directly.
> 
> > I was actually a little curious about what you've done in there that's why I dug into and did all those stuff otherwise there were easier ways as you mentioned.
> 
> Good dig!

The rewrite used to work with your page.something routes but it doesn't work with laravel normal routes unfortunately. It just doesn't load the laravel route after rewrite anymore which was a little bit expected.It doesn't need rewrite anyways since it comes up. But with no page so just setting a page would be enough.

```
Route::get('/test/{hello}',function ($hello){
    global $wp_query;
    $wp_query = new WP_Query([ 'p' => 1, 'post_type' => 'any' ]);
    while(have_posts()){
        the_post();
        the_title();
    }
});
```
This is the easiest and most convenient way to do this I guess.Nothing complicated it needs only 2 or 3 lines of code. (I didn't get the ID by its slug but well that's obviously easy.)

Now a helper function could do this all in a line.But the cleaner way still would be to implement this in the route Facade with a simple boolean flag as an option.

And about the paging convention.

/test/{hello}/{foo}/{bar}
This means test page with those arguments hello Foo and bar if you use it like this in Laravel you can't have any thing underneath test so no child page it test also works in WordPress.
/test/{hello}/soo/{foo}/{bar}
This however in WordPress could mean.
/test/*/soo/*/*
And it totally works with rewrite rules.
But in combination with laravel the soo makes it not work.So again the page could only be test not soo.

The only choice coming into play would be this.

Test/hello/{hi}

Now maybe somebody doesn't want to load hello page maybe want test page, or maybe a hello child page (which won't be routable anymore but still since it's in the database and editable from admin panel). 


So I think changing the Route facade to take a third argument as true or false for automatic taking the last piece before {} and if it is string instead of boolean it is a custom page.

I think this is the last piece of routing puzzle cause you've already done the rest of the routing features at its highest possible quality.

**Comment by yaquawa** [comment]
To be honest, I would never recommend anyone to do this with the WordPress route, because I think this kind of route is so confusing in terms of child pages.

But I'd like to give you a solution to get this worked.

Overwrite the `\App\Providers\RouteServiceProvider::registerWpRouter` with your own WpRouter Facade; or if you like you could create another package that rebinds the 'wpRouter' singleton so you can reuse it in other projects.


Create a class that extends `\Laraish\Routing\WpRouter`, overwrite the `post` method as below.

```php
    public function page($selectorOrAction, $actionOrMethods = null, $methods = null)
    {
        [$uri, $action, $methods] = $this->normalizeSignature('page', $selectorOrAction, $actionOrMethods, $methods);

        if ($uri !== 'page') {
            global $wp_rewrite;
            $pageName = Str::before($selectorOrAction, '/{');
            $rule = "^($pageName).+?(?:/([0-9]+))?/?$";
            
            if (!array_key_exists($rule, $wp_rewrite->rules)) {
                add_rewrite_rule($rule, 'index.php?pagename=$matches[1]&page=$matches[2]', 'top');
                $wp_rewrite->flush_rules(false);
            }

            return $this->addRoute(Str::after($uri, 'page.'), $action, $methods);
        }


        return $this->addRoute($uri, $action, $methods);
    }

```

**Comment by Stevemoretz** [comment]
Thank you for your time,awesome will give that a try today for sure.

And yeah when using this there shouldn't be any child pages underneath anymore cause it won't work anyways, but even if it does in some cases, you still get too much side effects that it's not worth it.So choosing either this way or a child page is the way to go not both of them.

Thanks again

**Comment by Stevemoretz** [comment]
> To be honest, I would never recommend anyone to do this with the WordPress route, because I think this kind of route is so confusing in terms of child pages.
> 
> But I'd like to give you a solution to get this worked.
> 
> Overwrite the `\App\Providers\RouteServiceProvider::registerWpRouter` with your own WpRouter class; or if you like you could create another package that rebinds the 'wpRouter' singleton so you can reuse it in other projects.
> 
> Create a class that extends `\Laraish\Routing\WpRouter`, overwrite the `post` method as below.
> 
> ```
>     public function page($selectorOrAction, $actionOrMethods = null, $methods = null)
>     {
>         [$uri, $action, $methods] = $this->normalizeSignature('page', $selectorOrAction, $actionOrMethods, $methods);
> 
>         if ($uri !== 'page') {
>             global $wp_rewrite;
>             $pageName = Str::before($selectorOrAction, '/{');
>             $rule = "^($pageName).+?(?:/([0-9]+))?/?$";
>             
>             if (!array_key_exists($rule, $wp_rewrite->rules)) {
>                 add_rewrite_rule($rule, 'index.php?pagename=$matches[1]&page=$matches[2]', 'top');
>                 $wp_rewrite->flush_rules(false);
>             }
> 
>             return $this->addRoute(Str::after($uri, 'page.'), $action, $methods);
>         }
> 
> 
>         return $this->addRoute($uri, $action, $methods);
>     }
> ```
> 
> notice that because this add a extra rewrite rule to wordpress, the first time you load the page won't work, it'll work for the second time onwards.
Just a little bit of change was needed to make it more subtle.It was also accepting routes with more or less than the defined arguments,also dot was not considered for multiple level routes.

```
    public function page($selectorOrAction, $actionOrMethods = null, $methods = null)
    {
        [$uri, $action, $methods] = $this->normalizeSignature('page', $selectorOrAction, $actionOrMethods, $methods);

        if ($uri !== 'page') {
            global $wp_rewrite;
            $pageName = preg_replace('/\./', '/', Str::before($selectorOrAction, '/{'));
            $paramCount = preg_match_all('/{.*?}/', $uri, $matches, PREG_SET_ORDER, 0);
            $param = '';
            for($i = 0; $i < $paramCount; $i++){$param .= '([^/]+)/';}
            $rule = "^($pageName)/?$param?$";

            if (!array_key_exists($rule, $wp_rewrite->rules)) {
                add_rewrite_rule($rule, 'index.php?pagename=$matches[1]&page=$matches[2]', 'top');
                $wp_rewrite->flush_rules(false);
            }
            return $this->addRoute(Str::after(preg_replace('/\./', '/', $uri), 'page/'), $action, $methods);
        }


        return $this->addRoute($uri, $action, $methods);
    }

```

Thanks again you're a genius I couldn't find this in a thousand years 😅👍

**Comment by Stevemoretz** [comment]
There is only one flaw here that I noticed now if you use somepage/100 it will try to paginate to page 100 of somepage instead of using this rewrite any idea how to disable pagination for a particular page?

**Comment by yaquawa** [comment]
change `index.php?pagename=$matches[1]&page=$matches[2]` to `index.php?pagename=$matches[1]` should work.

**Comment by Stevemoretz** [comment]
> change `index.php?pagename=$matches[1]&page=$matches[2]` to `index.php?pagename=$matches[1]` should work.

Thank you man, I'm a few days away from my laptop I'll check on it ASAP.

You're the best.

**Comment by Stevemoretz** [comment]
I'm closing this issue because it was getting out of topic.
Thanks for all your help yaquawa. 👍 You are the best.
