### ISSUE TITLE
Problem with WordPress redirect 

### ISSUE THREAD

**Issue by Stevemoretz** [laraish/laraish#19]
Hi WordPress for example created the hello-world post and now if on top of the file of api.php or web.php you define a laravel route and it is named as hello then you try to access it via for example site.test/api/hello it will redirect to the post of hello world site.test/hello-world instead of the api if I change the name of the route it works, so it's a kind of prorioty problem not routing problem.
How to fix this?

**Comment by yaquawa** [comment]
Try to place any Laravel routes before the wordpress's ones.

**Comment by Stevemoretz** [comment]
Thanks but that is exactly what what I've done the laravel route is at the top of the file. Would you mind giving it a test? Just create a /hello route at the top of the file and make sure your hello-world post is not deleted and then goto /hello it will take you to hello-world instead. 

Now there is a Plugin to disable this auto completion of WordPress totally which is great as a plan b. But if it could be fixed it was way better.

**Comment by yaquawa** [comment]
I think this is not an "issue", because that's the default behavior of WordPress right..?
I would suggest to leverage the plugin you found 🤝

**Comment by Stevemoretz** [comment]
It is default if you didn't have a hello page but since now you define it in Laravel, WordPress can't use that as a page and will autocorret it first if nothing was found then it loads the laravel page.The problem is like if you made something in Laravel routes then later a user of yours created a post that can cause your laravel route not to work anymore.

If there is no workaround to fix this.

Then I suggest you use the same Plugin as I told you because this problem might happen to your customers later on. And also add this known issue to your docs I guess.Anyways thank you I just wanted you to know this issue exists.

**Comment by yaquawa** [comment]
@Stevemoretz Thanks for letting me know this👍🏼
