### ISSUE TITLE
Installation via valet plus

### ISSUE THREAD

**Issue by rodmar35** [laraish/laraish#2]
Hi,

Thanks for your theme !

On mac i have installed Valet plus for local dev https://github.com/weprovide/valet-plus/
- nginx
- php 7
- composer
- wordpress

Mysql and webserver is running and in terminal, in the directory  /app/public/wp-content/themes i run the command "composer create-project --prefer-dist laraish/laraish theme1".

In terminal, i'v got this error : 
`Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255`

In "/app/public/wp-content/themes/theme1" i'v got directories and files generated : app, boostrap, config, database, public, resource, ...

Maybe this error is coming from ValetPlus and not your theme install. I'm not sure.
Could you help me ?
Thanks
Rodmar

**Comment by rodmar35** [comment]
I'v solved it.

It was due to error `Fatal error: Cannot redeclare __()`.

As explain here https://github.com/laraish/laraish/issues/1 I've had `Laraish\\Foundation\\ComposerScripts::renameHelperFunctions` to `post-autoload-dump` script in composer.json file then run a `composer update` command
 
`        "post-autoload-dump": [
            "Laraish\\Foundation\\ComposerScripts::renameHelperFunctions",
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]`

Rodmar

**Comment by mssoo7** [comment]
Class Laraish\Foundation\ComposerScripts is not autoloadable, can not call post-autoload-dump script when i update composer
and not working with
"post-autoload-dump": [ "Laraish\\Foundation\\ComposerScripts::renameHelperFunctions", "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump", "@php artisan package:discover" ]

**Comment by yaquawa** [comment]
@mssoo7 For now you can simply remove `Laraish\Foundation\ComposerScripts::renameHelperFunctions`, i'll fix it later on.
