### ISSUE TITLE
Question about docs {$template_slug}

### ISSUE THREAD

**Issue by Stevemoretz** [laraish/laraish#20]
Hi thank you for the new major update, would you mind explaining usage of :
{$template_slug}.blade.php
An example would be great.

And by the way header and footer and sidebar templates are not supported right?

**Comment by Stevemoretz** [comment]
I create template-sm.php  :
`<?php
/**
 * Template Name: template-sm
 * Template Post Type: post, page
 *
 * @package WordPress
 */
`

 at the root of laravel.

Then created /resources/views/wp/template/template-sm.blade.php:
`This is my stuff
`
Chosen the template for a page and the blade file does not load and also the laraish is not loading the route at all because the view debugger doesn't exit.

**Comment by yaquawa** [comment]
you should register your templates at here
https://github.com/laraish/laraish/blob/master/config/theme.php#L167-L176

**Comment by Stevemoretz** [comment]
> you should register your templates at here
> https://github.com/laraish/laraish/blob/master/config/theme.php#L167-L176

OH porden me, it missed that this was driving me nuts. Thank you so much.I'll give it a try and close this issue in a few minutes.

**Comment by Stevemoretz** [comment]
> you should register your templates at here
> https://github.com/laraish/laraish/blob/master/config/theme.php#L167-L176

That worked but still it's not looking like it's routing via lariash because there is no ViewDebugger.
Also there is no way to use WpRoute for template right?

It's not possible?

**Comment by yaquawa** [comment]
Did you put the template file to `wp/template/template-sm.blade.php` and have `WpRoute::autoDiscovery();` in your route file?

**Comment by Stevemoretz** [comment]
Sure I put wp/template/template-sm.blade.php and also I have WpRoute::autoDiscovery(); and in theme I added " 
`        [
            'post_type' => ['page', 'post'],
            'name' => 'template-sm'
        ]
`
And it works and the page loads with the blade.php file and everything works but there is no ViewDebugger in the console,and also couldn't find something like:
`WpRoute::template([Page::class, 'index']);`
to get it working since the 
`WpRoute::page([Page::class, 'index']);`
doesn't work anymore with changing from the default template.Is there any way to use action controller for the template files?

**Comment by yaquawa** [comment]
you should call `wp_footer()` to get the view debugger worked.

no plan to add a template route currently, just sticking with the naming convention is good enough I think.

**Comment by Stevemoretz** [comment]
Oh silly me you're right it already works no need for template route actually I thought something's wrong with template routing which it wasn't.Something was wrong with me :D.
Looks like you've taken care of everything already.

Thank you so much.

**Comment by yaquawa** [comment]
Well you could specify your own template view and pass view data to it, just do it in the controller.

>  You can refer the template name by `$post->page_template`.
Chances are that you are going to lookup `$post->page_template` in
controllers to determine which view is going to be used.

**Comment by yaquawa** [comment]
By the way, if you use `WpRoute::autoDiscovery();`, the framework is going to look a class `\App\Models\Wp\Template\ TemplateSm` to use, if you need a controller to do complex logic, you might want create such a controller.

**Comment by Stevemoretz** [comment]
Thanks for these nice informations, I'll check on it today again.
