### ISSUE TITLE
How to update to the new version

### ISSUE THREAD

**Issue by Stevemoretz** [laraish/laraish#21]
Hi I've done a lot of basic code on the previous version is it possible to keep them and update the project without recreating using composer create-project?

How to update then? thanks.

**Comment by yaquawa** [comment]
* change namespace `Laraish\WpSupport` to `Laraish\Support\Wp`
* replace `\App\Providers\RouteServiceProvider` with the new one
* move `routes/web.php` to `routes/wp.php`

I think this is enough.
