### ISSUE TITLE
Will there be a laravel 8 support

### ISSUE THREAD

**Issue by ThinkDevStudios** [laraish/laraish#22]
Hi! When will Laraish be upgraded to work with Laravel 8?

**Comment by yaquawa** [comment]
I'll handle this very soon.

**Comment by flip-9** [comment]
Checking in if we should start our project in L 7 or wait a bit longer for L8 support. AMAZING work so far guys!

**Comment by yaquawa** [comment]
@ThinkDevStudios @flip-9 I've just upgraded it to Laravel 8.
