### ISSUE TITLE
Lost of Laraish global post variable when using a page template

### ISSUE THREAD

**Issue by MDGDesign** [laraish/laraish#23]
Hey great work!

I really like this.

I am testing it to eventually use it in my WP projects and I am trying presently to set a page template.

Not much info on how to really do it but I was able to figure it out.

During the process I noticed that the **Laraish $post** variable becomes NULL when a page uses **a template**.
Therefore in the Controller Page index method, I have to grab the **global $post** variable and past it to the view. 

So in the view, this becomes **$post->post_title** and **$post->post_content** as an example (**not $post->title**).

What I did:

- Registered the template in the config > theme.php with some extra values for the path to the template.
- Created a folder in views > wp > templates > some_template.blade.php.
- Created the methods and functionality to check if a page as a template and default if not.

I am not sure if this is a bug or due to my limited understanding and I am creating the bug!!

Thanks!

**Comment by yaquawa** [comment]
The directory name should be `template` but not `templates`.

**Comment by MDGDesign** [comment]
Hello Yaquawa,

Thanks for this important detail. That spkipped my attention.
