### ISSUE TITLE
Can't Access Regular Route

### ISSUE THREAD

**Issue by Moaz-e** [laraish/laraish#26]
Hello,

I am excited to use this package , after installing the package i uncommit the route in web.php and dump some text as showing in this pic :
 ![image](https://user-images.githubusercontent.com/37017532/97303049-edca7300-186a-11eb-83a5-4d8adca939a2.png)

but when call the route as "localhost:10080/ShiblyMarketing/foobar" i get "404 Not Found"
and i don't have any text dumping .

knowing that when dumping on 'wp.php' and call route "localhost:10080/ShiblyMarketing/home"
the home page opened and the dump text showing normally :
![image](https://user-images.githubusercontent.com/37017532/97303708-cde77f00-186b-11eb-84e5-c6bc3202c007.png)

please can anyone tell me what the problem .

thanks.

**Comment by yaquawa** [comment]
> but when call the route as "localhost:10080/ShiblyMarketing/foobar" i get "404 Not Found"

Your route URI should be written as `/ShiblyMarketing/foobar` where yours was `/foobar`

**Comment by Moaz-e** [comment]
> Your route URI should be written as `/ShiblyMarketing/foobar` where yours was `/foobar`

Sorry i don't understand what the change in URL ,  i really written `/Shibly Marketing/foobar` and get '404 Not Found'
Please note dumping issue as well

**Comment by yaquawa** [comment]
Could you show me your actual source code but not the Pseudo one?
Honestly, I don't know what you're trying to achieve.

**Comment by Moaz-e** [comment]
I installed the wordpress and intall the laraish in the theme folder and i writen a regular route in web.php file but when call this route i getten '404 Not Found' ,
knowing that when call route from wp.php all route its work normally .

this my web.php file content :

```
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
dump("Web Route");

Route::get('/foobar', function () {
    return view('wp.home');
});
```

and this the wp.php content :

```
use App\Http\Controllers\Wp\Home;
use App\Http\Controllers\Wp\Page;
use App\Http\Controllers\Wp\Post;
use Laraish\Support\Facades\WpRoute;

dump("WordPress Route");

WpRoute::home([Home::class, 'index']);
WpRoute::page([Page::class, 'index']);
WpRoute::post('post', [Post::class, 'index']);
WpRoute::autoDiscovery();
```

**Comment by Moaz-e** [comment]
> 
> 
> Could you show me your actual source code but not the Pseudo one?
> Honestly, I can't see what you're trying to achieve.

i think there is problem and no going inside api.php or web.php ,
i don't know what this problem i really want help to understand why not go inside this files 'api.php' and 'web.php' .

**Comment by yaquawa** [comment]
what's the actual URL that shows you a 404 page?

**Comment by Moaz-e** [comment]
> 
> 
> what's the actual URL that shows you a 404 page?

localhost:10080/ShiblyMarketing/foobar

**Comment by yaquawa** [comment]
The problem is that you define the route as `/foobar` which not matches your url `localhost:10080/ShiblyMarketing/foobar`.
The counterpart of route `/foobar` is `localhost:10080/foobar`.

**Comment by Moaz-e** [comment]
No i am work with xxamp and the base url to go inside the project 'localhost:10080/ShiblyMarketing' and this url get me home page .
when call 'localhost:10080/foobar' i getting "The requested URL was not found on this server" .

**Comment by yaquawa** [comment]
well, that's the correct behavior. for that case, you should write your route as `/ShiblyMarketing/foobar`

**Comment by Moaz-e** [comment]
> 
> 
> well, that's the correct behavior. for your case, you should write your route as `/ShiblyMarketing/foobar`

that what i try to understand when define any url inside 'web.php' and 'api.php' not work why !?.

It does not print what is inside the dump("Web Route");  even which means it does not enter it. 
While he is print dump("WordPress Route");

please can help me to know what the problem .

**Comment by yaquawa** [comment]
Sorry but I can't see what you're trying to ask for.

I assume If you are curious about why the `dump("Web Route");` executed even if there wasn't any matched routes.
The `web.php` always get evaluated on every incoming request.

**Comment by Moaz-e** [comment]
The problem is that it never gets inside the `web.php` and nothing is dumping .

**Comment by yaquawa** [comment]
oh, I see the problem now. 
I have fixed the issue. you can `composer update` to update it.

**Comment by Moaz-e** [comment]
oh thanks really, it works now 🥳
