### ISSUE TITLE
Array to string conversion 

### ISSUE THREAD

**Issue by christiancannata** [laraish/laraish#29]
I am trying to make a sample home route after the installation but it seems it's not working.

<img width="1070" alt="Schermata 2020-11-13 alle 19 28 28" src="https://user-images.githubusercontent.com/4604959/99113008-758fdb80-25e6-11eb-8819-f955262410a3.png">
<img width="567" alt="Schermata 2020-11-13 alle 19 28 57" src="https://user-images.githubusercontent.com/4604959/99113022-7b85bc80-25e6-11eb-9282-c7c80b4cacff.png">

**Comment by yaquawa** [comment]
This is a bug, I have fixed it, now you can run `composer update` to update.
