### ISSUE TITLE
When using laraish with Brizy Pro load times goes up as high as 5 sec

### ISSUE THREAD

**Issue by ThinkDevStudios** [laraish/laraish#31]
Hi! When I am using Laraish theme with Brizy Pro. The waterfall/load times can go as high as 5 secs. It goes back to normal when using an ordinary theme. I'm not sure if it's due to the routes?

What would be the best thing to do? connect the routes to the Brizy builder theme or put every page in the routes?

**Comment by yaquawa** [comment]
Sorry, I've never used it, so I can't give any helpful advice.
In my opinion, if you are using some kind of page builder, you don't need laraish.

**Comment by ThinkDevStudios** [comment]
I'm just using Brizy builder for the landing pages and other pages and using Laraish for the recruitment system that I created. I was previously using Themosis Framework but I can't install Laravel packages in that framework that's why I switched to Laraish.
