### ISSUE TITLE
Link the assets

### ISSUE THREAD

**Issue by Alkasih** [laraish/laraish#32]
Hi I tried to link the assets like css, js, imgs and etc. But it doesn't seem to work. 

		<link href="{{ URL::asset('/js/jquery.js') }}" rel="script">

The file is under `wp-content/themes/laraish/public/css`

**Comment by yaquawa** [comment]
use `public_url`
```
<link href="{{ public_url('/js/jquery.js') }}" rel="script">
```

**Comment by Alkasih** [comment]
Thanks, it works. Btw, it loads anything too long.
