### ISSUE TITLE
Help with WooCommerce templates

### ISSUE THREAD

**Issue by castorstudio** [laraish/laraish#37]
Hi, I need your help to configure laraish with woocommerce templates.

I have been actively working with laraish, it's really awesome, but I ran into a problem when integrating with woocommerce.

The woocommerce endpoints like the cart or the checkout page work smoothly and the template loads fine and shows the correct information. The problem occurs with the store page and the product single page, where only the title is shown and the content is not visible.

I use the `WpRoute::post('product', [Post::class, 'woocommerceProduct']);` route to reference a specific product, and it works correctly, but it does not show the default woocommerce template, but the one I add in the controller.

The same thing happens with the store page, where the page loads but only the title is shown, the catalog is hidden as it does not load the default woocommerce template.

I have tried modifying the routes, the views or the controller, but I can't find the formula to make them display correctly.

Please help me or guide me on how to achieve this

**Comment by yaquawa** [comment]
This is the correct behavior, woocommerce template won't be used if you are using blade template.

**Comment by castorstudio** [comment]
I know, I did it to test if it was working right, and if it was.
The problem is that when I just use `WpRoute::autoDiscovery();` none of those woocommerce pages are displayed correctly... just the title, but not the content.

**Comment by castorstudio** [comment]
I know, but the woocommerce template loads even when the `/routes/wp.php` file is empty.
Situation 1: `/routes/wp.php` file empty
I go to the url: mysite.local/shop
Expected result: error 404
Result obtained: store page showing all products

Situation 2: `/routes/wp.php` file empty
I go to the url: mysite.local
Expected result: error 404
Result obtained: error 404

Any other route throws the expected 404 error considering that the `/routes/wp.php` file is empty.

Why does this behavior happen?

**Comment by yaquawa** [comment]
That's because you don't have any *.php templates under your theme I guess.

**Comment by castorstudio** [comment]
but how would laraish know where the templates are, if it's not even reading the routes file?

I do a test, in the /routes/wp.php file I add only the following code: <?php wp_die('die from routes/wp.php'); ?> and if I go to the woocommerce "shop" page, it shows without problems and should throw the wordpress error message.
If I go to any other route, the error message is as expected.

I imagine woocommerce is bypassing the rewrite rules at a level or time where laraish doesn't quite get there

**Comment by yaquawa** [comment]
You can't use Blade template if you are using *.php tempalte.
The Laraish take preference over *.php template, if it can't find any *.php template, then try to use `/routes/wp.php`.

**Comment by brutalhost** [comment]
I faced the same problem with WooCommerce. I create templates that should be used by the page (for example, the product page uses archive-product.php, archive.php, index.php), but none are picked up. WpRoute::autoDiscovery() is enabled. The archive page was originally available in laraish, I created duplicates of this template without blade - the result was zero.

**Comment by brutalhost** [comment]
It looks like this is laraish's problem. On standard Wordpress pages I get the template name "index.php". On the Woocommerce product page it is ".../wp-content/plugins/classic-commerce-master/templates/archive-product.php". This means that it does not use the archive page and its alternatives.
