### ISSUE TITLE
Does not work with xammp with php version 8.0.5

### ISSUE THREAD

**Issue by Alexlytle** [laraish/laraish#38]
When I try to install in the terminal with a fresh installation of xammp and composer I get this error

 Problem 1
    - phpunit/phpunit[7.0.0, ..., 7.5.20] require php ^7.1 -> your php version (8.0.5) does not satisfy that requirement.
    - Root composer.json requires phpunit/phpunit ~7.0 -> satisfiable by phpunit/phpunit[7.0.0, ..., 7.5.20].

**Comment by yaquawa** [comment]
remove [phpunit](https://github.com/laraish/laraish/blob/master/composer.json#L20) if you want to use ver8.
