### ISSUE TITLE
Cant install Vue JS into laraish 

### ISSUE THREAD

**Issue by Alexlytle** [laraish/laraish#41]
I know this may be a issue with me but this may help someone else. Here is my code I have trying to get vue js installed with laravel mix. Please help. I have no errors in the terminal but i get this in the browser console.
`app.js?1621979265:11980 Uncaught Error: Cannot find module './components/HelloWorld.vue'`
| What would be the easiest way to get vue 3 in laraish 

 app.js?1621979265:11980 Uncaught Error: Cannot find module './components/HelloWorld.vue'

![image](https://user-images.githubusercontent.com/44213950/119576347-6ba51d00-bd6d-11eb-9d8a-2e36278787df.png)

![image](https://user-images.githubusercontent.com/44213950/119576419-9000f980-bd6d-11eb-805d-0700deb0aa2e.png)

![image](https://user-images.githubusercontent.com/44213950/119576452-9f804280-bd6d-11eb-8dae-cab0b6c488ab.png)

![image](https://user-images.githubusercontent.com/44213950/119576504-b9218a00-bd6d-11eb-88bb-925ef8ce16a9.png)

![image](https://user-images.githubusercontent.com/44213950/119578226-faffff80-bd70-11eb-9a65-d1c342e01070.png)

**Comment by yaquawa** [comment]
This is an issue related to laravel-mix 6.

please use  `"laravel-mix": "^5.0.1"`, or just post this to `laravel-mix`.
