### ISSUE TITLE
WP_Query 

### ISSUE THREAD

**Issue by Alexlytle** [laraish/laraish#45]
I understand this is not a bug but i feel like this can help others. I'm trying to do something like the following. The issue is WP_Query is not found. What would be the  best way to get something like this working.
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class Test extends Controller
{
    public function index()
    {
        $args = array(
            'post_type' => 'product',
            'posts_per_page' => 12
            );
            
          $query = new WP_Query( $args );
        return view('view.test',[$query]);
    }
}

```

**Comment by yaquawa** [comment]
you should add the root namespace: `new \WP_Query( $args ); `

**Comment by Alexlytle** [comment]
Could you please provide the exact names pacing

I have tried 
`namespace  WP_Query;`

**Comment by Alexlytle** [comment]
Thank you !
