### ISSUE TITLE
ACF and Images 

### ISSUE THREAD

**Issue by Alexlytle** [laraish/laraish#46]
Displaying ACF images don't seem to work. Maby I'm doing something wrong. In traditional PHP it would be
` $image = get_field('collection_image');
  <img src="<?php echo esc_url($image['url']); ?>" alt="<?php echo esc_attr($image['alt']); ?>"  />
`

What would be the best way to get Images with ACF in Laraish?

**Comment by Alexlytle** [comment]
I was able to do it this way 

`              @foreach ($post->posts as $post)
                      <img src="{{wp_get_attachment_image_src(get_post_meta($post->ID,'collection_image',true),'full')[0]}}" alt=""  />
                      `

**Comment by yaquawa** [comment]
see https://github.com/laraish/laraish#work-with-acf

**Comment by Alexlytle** [comment]
That doesn't explain anything besides getting the name value

**Comment by yaquawa** [comment]
You must use use [models](https://github.com/laraish/laraish#models) if you want to get the custom field that was created by acf from models, otherwise you want to use the good old `get_field` to get it.

**Comment by Alexlytle** [comment]
Thank you :) Since I'm not the best with Laravel I will stick with the
WordPress way
