### ISSUE TITLE
WpRoute::class - "Array to string conversion" exception

### ISSUE THREAD

**Issue by boxybird** [laraish/laraish#49]
Hello! I just came across this package, and wow, very cool. I thank you in advance for any help!

I was giving it a test drive and ran into a `WpRoute::class` issue:

```
// These work just fine.
WpRoute::page('sample-page', [Page::class, 'index']);
WpRoute::author('john', [Author::class, 'index']);

// Throw "Array to string conversion" exceptions.
WpRoute::page([Page::class, 'index']);
WpRoute::author([Author::class, 'index']);
```
It looks like the error has something to do with `$selector`:

![Screenshot 2021-09-14 071518](https://user-images.githubusercontent.com/18317878/133264501-0bb70db0-5bb5-4a4d-bc0f-059e46bba364.png)
 
![laraish test_](https://user-images.githubusercontent.com/18317878/133263823-ececd2b8-dca1-4509-80e0-36300cec9593.png)

**Comment by yousseffatihi** [comment]
I have faced the same problem after upgrading php7 to php8, All the thanks to Allah I fixed it just by add the callable [ selectorOrAction ] like this : 

`WpRoute::page('page', [Page::class, 'index']);`

**Comment by yousseffatihi** [comment]
If it stills not working then try this in the WpRouter.php in the line 262:
replace this code `$uri = "{$baseUri}.{$selector}";` by this one `$uri = implode('.', [$baseUri, $selector]);`
