### ISSUE TITLE
Featured post image not showing on single

### ISSUE THREAD

**Issue by fabianwurk** [laraish/laraish#5]
I've tried adding a Featured Image to a single post but it doesn't seem to be showing that image?

`                @if($post->hasPostThumbnail)
                    <img src="{{ $post->thumbnail->url }}" class="post-thumbnail">
                @endif`

**Comment by fabianwurk** [comment]
It seems to be issue with the conditional statement as this works fine without the @if:

`<img src="{{ $post->thumbnail->url }}" class="post-thumbnail"> `

**Comment by yaquawa** [comment]
The method name is `hasThumbnail`.

```php
@if($post->hasThumbnail)
    <img src="{{ $post->thumbnail->url }}" class="post-thumbnail">
@endif
```
