### ISSUE TITLE
Not installing properly

### ISSUE THREAD

**Issue by cletuskingdom** [laraish/laraish#56]
I tried installing following the instruction, and this is what i get; composer update and install didn't resolve it.
![image](https://user-images.githubusercontent.com/38631504/147789324-87eb8af5-e99a-4450-977c-d04531a59817.png)

**Comment by cletuskingdom** [comment]
Here's the error:

`PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php:826
Stack trace:
#0 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php(826): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\Container\Container->resolveDependencies()
#2 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build()
#3 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve()
#4 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->make()
#5 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php(256): Illuminate\Foundation\Application->make()
#6 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php(764): Illuminate\Container\Container->Illuminate\Container\{closure}()
#7 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build()
#8 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve()
#9 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->make()
#10 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(159): Illuminate\Foundation\Application->make()
#11 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(101): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#12 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(87): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole()
#13 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#14 {main}
  thrown in /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 826
<!DOCTYPE html>
<html lang="en-US">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="viewport" content="width=device-width">
		<meta name='robots' content='noindex, nofollow' />
	<title>WordPress &rsaquo; Error</title>
	<style type="text/css">
		html {
			background: #f1f1f1;
		}
		body {
			background: #fff;
			border: 1px solid #ccd0d4;
			color: #444;
			font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
			margin: 2em auto;
			padding: 1em 2em;
			max-width: 700px;
			-webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, .04);
			box-shadow: 0 1px 1px rgba(0, 0, 0, .04);
		}
		h1 {
			border-bottom: 1px solid #dadada;
			clear: both;
			color: #666;
			font-size: 24px;
			margin: 30px 0 0 0;
			padding: 0;
			padding-bottom: 7px;
		}
		#error-page {
			margin-top: 50px;
		}
		#error-page p,
		#error-page .wp-die-message {
			font-size: 14px;
			line-height: 1.5;
			margin: 25px 0 20px;
		}
		#error-page code {
			font-family: Consolas, Monaco, monospace;
		}
		ul li {
			margin-bottom: 10px;
			font-size: 14px ;
		}
		a {
			color: #0073aa;
		}
		a:hover,
		a:active {
			color: #006799;
		}
		a:focus {
			color: #124964;
			-webkit-box-shadow:
				0 0 0 1px #5b9dd9,
				0 0 2px 1px rgba(30, 140, 190, 0.8);
			box-shadow:
				0 0 0 1px #5b9dd9,
				0 0 2px 1px rgba(30, 140, 190, 0.8);
			outline: none;
		}
		.button {
			background: #f3f5f6;
			border: 1px solid #016087;
			color: #016087;
			display: inline-block;
			text-decoration: none;
			font-size: 13px;
			line-height: 2;
			height: 28px;
			margin: 0;
			padding: 0 10px 1px;
			cursor: pointer;
			-webkit-border-radius: 3px;
			-webkit-appearance: none;
			border-radius: 3px;
			white-space: nowrap;
			-webkit-box-sizing: border-box;
			-moz-box-sizing:    border-box;
			box-sizing:         border-box;

			vertical-align: top;
		}

		.button.button-large {
			line-height: 2.30769231;
			min-height: 32px;
			padding: 0 12px;
		}

		.button:hover,
		.button:focus {
			background: #f1f1f1;
		}

		.button:focus {
			background: #f3f5f6;
			border-color: #007cba;
			-webkit-box-shadow: 0 0 0 1px #007cba;
			box-shadow: 0 0 0 1px #007cba;
			color: #016087;
			outline: 2px solid transparent;
			outline-offset: 0;
		}

		.button:active {
			background: #f3f5f6;
			border-color: #7e8993;
			-webkit-box-shadow: none;
			box-shadow: none;
		}

			</style>
</head>
<body id="error-page">
	<div class="wp-die-message"><p>There has been a critical error on this website.</p><p><a href="https://wordpress.org/support/article/faq-troubleshooting/">Learn more about troubleshooting WordPress.</a></p></div></body>
</html>
	PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php:826
Stack trace:
#0 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php(826): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\Container\Container->resolveDependencies()
#2 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build()
#3 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve()
#4 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->make()
#5 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php(256): Illuminate\Foundation\Application->make()
#6 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php(764): Illuminate\Container\Container->Illuminate\Container\{closure}()
#7 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build()
#8 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve()
#9 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->make()
#10 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(159): Illuminate\Foundation\Application->make()
#11 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(101): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#12 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(87): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole()
#13 /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#14 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#15 {main}
  thrown in /var/www/html/wordpress_project/wp-content/themes/beautifyme/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 826`

**Comment by cletuskingdom** [comment]
running any command gives me this error

**Comment by yaquawa** [comment]
Are you using php8? currently only support php7.

**Comment by cletuskingdom** [comment]
Yes, I'm using php8; I'll try php7 and give you the feedback. Thanks for responding.
