### ISSUE TITLE
Laravel Package 

### ISSUE THREAD

**Issue by beingmohit** [laraish/laraish#7]
Nice work @yaquawa 

Wondering if this can be converted into a laravel package so that users can seamlessly upgrade laravel or plug into their existing application

**Comment by beingmohit** [comment]
Also I am exploring [corcel](https://github.com/corcel/corcel) for Eloquent models in laraish

**Comment by RayhanYulanda** [comment]
> Also I am exploring [corcel](https://github.com/corcel/corcel) for Eloquent models in laraish

Can you explain how to integrate laravel with corcel and laraish?
