### ISSUE TITLE
routes bug

### ISSUE THREAD

**Issue by itsho15** [laraish/laraish#8]
hello , great work but i have problem when i try to use web.php any route is not working
it`s give me an error page 500
Whoops, something went wrong on our servers.

i`m using last version of wordpress 5.0.3

**Comment by yaquawa** [comment]
I'm using 5.0.3 too, nothing everything works properly here.
So I'm afraid it's not the framework's issue.

**Comment by itsho15** [comment]
The problem happen because i try to use custom router after the wordpress routes and when i used it before them it’s work fine , i have other issue and i can’t fix it tell now see it if you Are not bussy

**Comment by yaquawa** [comment]
Yeah, you must have your custom routes be placed before the WordPress's, that's how the routing works.
